"""
AWS AgentCore Integration Module

This module provides adapters and configuration for AWS Bedrock AgentCore primitives:
- Runtime: Serverless agent execution
- Memory: Persistent knowledge storage with semantic search
- Code Interpreter: Secure code execution in isolated sandboxes
- Browser: Cloud-based browser automation
- Gateway: MCP server integration and API connectivity
"""

from .config import AgentCoreConfig, get_agentcore_config, get_config
from .models import (
    SessionStatus,
    RuntimeStatus,
    CodeInterpreterSession,
    BrowserSession,
    CodeExecutionResult,
    ShellCommandResult,
    NavigationResult,
    ActionResult,
    ExtractionResult,
    ScreenshotResult,
    RuntimeSession,
    RuntimeDeployment,
    RuntimeExecutionResult,
    MemoryResource,
    StoredMessage,
    MCPServerDeployment,
    MCPToolInvocationResult,
    GatewayConfig,
    serialize_session,
    deserialize_session,
    serialize_result,
    deserialize_result,
)
from .errors import (
    AgentCoreError,
    AgentCoreConfigurationError,
    AgentCoreSessionError,
    AgentCoreExecutionError,
    AgentCoreBrowserError,
    AgentCoreRetryableError,
    AgentCoreNonRetryableError,
    ThrottlingError,
    ServiceUnavailableError,
    NetworkError,
    AuthenticationError,
    AuthorizationError,
    ResourceNotFoundError,
    ValidationError,
    AgentCoreTenantError,
    is_retryable_error,
    with_retry,
    redact_sensitive_data,
    safe_log,
    # Phase 10: Enhanced error handling
    ErrorSeverity,
    ErrorCategory,
    ErrorContext,
    ErrorAccumulation,
    MultiError,
    get_error_category,
    error_boundary,
    with_fallback,
    execute_batch_with_tolerance,
    safe_format,
)
from .adapters.runtime import AgentCoreRuntimeAdapter
from .adapters.memory import AgentCoreMemoryAdapter
from .adapters.code_interpreter import AgentCoreCodeInterpreterAdapter
from .adapters.browser import AgentCoreBrowserAdapter
from .adapters.gateway import AgentCoreGatewayAdapter
from .utils import (
    substitute_variables,
    extract_variables,
    validate_template,
    substitute_in_dict,
)
from .middleware import (
    TenantContext,
    TenantMiddleware,
    TenantContextManager,
    get_tenant_context,
    require_tenant_context,
    verify_tenant_access,
)
from .registry import (
    ToolMetadata,
    ToolCategory,
    ToolRegistry,
    get_tool_registry,
    reset_tool_registry,
)
from .services import Tier  # Phase 7: Subscription tier enum for MCP catalog filtering
from .security import (
    Permission,
    PermissionSet,
    APIKey,
    APIKeyManager,
    APIKeyScope,
    Role,
    RoleAssignment,
    RoleManager,
)  # Phase 7: Security module for API keys and permissions
from .billing import (
    UsageMetrics,
    CreditCost,
    UsageTracker,
    get_usage_tracker,
    track_agent_execution,
    complete_agent_execution,
)  # Phase 8: Billing and usage tracking
from .observability import (
    CloudWatchClient,
    AlertingService,
    MetricsCollector,
    HealthChecker,
    PerformanceMonitor,
)  # Phase 9: Observability and monitoring
from .validation import (
    PHASE_10_REGION as VALIDATION_REGION,
    ValidationSeverity,
    ValidationCategory,
    ValidationIssue,
    ValidationResult,
    ValidationRule,
    ConfigValidator,
    get_config_validator,
    validate_config,
    validate_config_or_raise,
    register_validation_rule,
)  # Phase 10: Configuration validation
from .cache import (
    PHASE_10_REGION as CACHE_REGION,
    CacheEntityType,
    CachePolicy,
    DEFAULT_POLICIES,
    CacheEntry,
    CacheStats,
    AgentCoreCache,
    CacheManager,
    cached,
    get_cache,
    get_cache_manager,
    initialize_cache,
    initialize_cache_manager,
    close_cache,
    close_cache_manager,
)  # Phase 10: Caching layer
from .logging_utils import (
    LogLevel,
    LogCategory,
    LogContext,
    StructuredLog,
    AgentCoreLogger,
    JsonFormatter,
    get_logger,
    log_execution_time,
    log_tenant_action,
    PerformanceLogger,
    redact_value,
    redact_dict,
    SENSITIVE_KEYS,
)  # Phase 10: Logging enhancements
from .api_docs import (
    HTTPStatus,
    APIResponse,
    ErrorDetail,
    PaginationInfo,
    PaginatedResponse,
    APIDocHelper,
    ResponseBuilder,
    document_endpoint,
    ExampleGenerator,
    get_openapi_schema,
    AGENTCORE_TAGS,
)  # Phase 10: API documentation helpers
from .rate_limiting import (
    PHASE_10_REGION as RATE_LIMITING_REGION,
    RateLimitScope,
    RateLimitAlgorithm,
    RateLimitRule,
    RateLimitResult,
    TIER_RATE_LIMITS,
    TokenBucket,
    SlidingWindowCounter,
    DistributedRateLimiter,
    RateLimiterManager,
    RateLimitError,
    rate_limit,
    get_rate_limiter,
    check_rate_limit,
)  # Phase 10: Rate limiting utilities
from .performance import (
    BatchPriority,
    BatchItem,
    BatchResult,
    BatchConfig,
    BatchProcessor,
    RuntimeBatchProcessor,
    get_batch_processor,
    get_runtime_batch_processor,
    PoolState,
    ConnectionType,
    PooledConnection,
    PoolConfig,
    PoolStats,
    ConnectionPool,
    RuntimeConnectionPool,
    AcquireContext,
    get_connection_pool,
    initialize_pools,
    close_pools,
    ShutdownState,
    ShutdownPriority,
    ShutdownHook,
    ShutdownResult,
    ShutdownConfig,
    GracefulShutdown,
    AgentCoreShutdownManager,
    get_shutdown_manager,
    initialize_shutdown,
    trigger_shutdown,
    ShutdownGuard,
)  # Phase 10: Performance optimization

__all__ = [
    "AgentCoreConfig",
    "get_agentcore_config",
    "get_config",
    "SessionStatus",
    "RuntimeStatus",
    "CodeInterpreterSession",
    "BrowserSession",
    "CodeExecutionResult",
    "ShellCommandResult",
    "NavigationResult",
    "ActionResult",
    "ExtractionResult",
    "ScreenshotResult",
    "RuntimeSession",
    "RuntimeDeployment",
    "RuntimeExecutionResult",
    "MemoryResource",
    "StoredMessage",
    "MCPServerDeployment",
    "MCPToolInvocationResult",
    "GatewayConfig",
    "serialize_session",
    "deserialize_session",
    "serialize_result",
    "deserialize_result",
    "AgentCoreError",
    "AgentCoreConfigurationError",
    "AgentCoreSessionError",
    "AgentCoreExecutionError",
    "AgentCoreBrowserError",
    "AgentCoreRetryableError",
    "AgentCoreNonRetryableError",
    "ThrottlingError",
    "ServiceUnavailableError",
    "NetworkError",
    "AuthenticationError",
    "AuthorizationError",
    "ResourceNotFoundError",
    "ValidationError",
    "AgentCoreTenantError",
    "is_retryable_error",
    "with_retry",
    "redact_sensitive_data",
    "safe_log",
    # Phase 10: Enhanced error handling
    "ErrorSeverity",
    "ErrorCategory",
    "ErrorContext",
    "ErrorAccumulation",
    "MultiError",
    "get_error_category",
    "error_boundary",
    "with_fallback",
    "execute_batch_with_tolerance",
    "safe_format",
    "AgentCoreRuntimeAdapter",
    "AgentCoreMemoryAdapter",
    "AgentCoreCodeInterpreterAdapter",
    "AgentCoreBrowserAdapter",
    "AgentCoreGatewayAdapter",
    "substitute_variables",
    "extract_variables",
    "validate_template",
    "substitute_in_dict",
    "TenantContext",
    "TenantMiddleware",
    "TenantContextManager",
    "get_tenant_context",
    "require_tenant_context",
    "verify_tenant_access",
    "ToolMetadata",
    "ToolCategory",
    "ToolRegistry",
    "get_tool_registry",
    "reset_tool_registry",
    "Tier",  # Phase 7: Subscription tier enum for MCP catalog filtering
    "Permission",  # Phase 7: Permission enum for RBAC
    "PermissionSet",  # Phase 7: Permission sets for common use cases
    "APIKey",  # Phase 7: API key model
    "APIKeyManager",  # Phase 7: API key lifecycle manager
    "APIKeyScope",  # Phase 7: API key scopes
    "Role",  # Phase 7: RBAC role enum
    "RoleAssignment",  # Phase 7: RBAC role assignment
    "RoleManager",  # Phase 7: RBAC role manager
    # Phase 9: Observability
    "CloudWatchClient",
    "AlertingService",
    "MetricsCollector",
    "HealthChecker",
    "PerformanceMonitor",
    # Phase 10: Validation
    "PHASE_10_REGION",
    "ValidationSeverity",
    "ValidationCategory",
    "ValidationIssue",
    "ValidationResult",
    "ValidationRule",
    "ConfigValidator",
    "get_config_validator",
    "validate_config",
    "validate_config_or_raise",
    "register_validation_rule",
    # Phase 10: Caching
    "CacheEntityType",
    "CachePolicy",
    "DEFAULT_POLICIES",
    "CacheEntry",
    "CacheStats",
    "AgentCoreCache",
    "CacheManager",
    "cached",
    "get_cache",
    "get_cache_manager",
    "initialize_cache",
    "initialize_cache_manager",
    "close_cache",
    "close_cache_manager",
    # Phase 10: Performance
    "BatchPriority",
    "BatchItem",
    "BatchResult",
    "BatchConfig",
    "BatchProcessor",
    "RuntimeBatchProcessor",
    "get_batch_processor",
    "get_runtime_batch_processor",
    "PoolState",
    "ConnectionType",
    "PooledConnection",
    "PoolConfig",
    "PoolStats",
    "ConnectionPool",
    "RuntimeConnectionPool",
    "AcquireContext",
    "get_connection_pool",
    "initialize_pools",
    "close_pools",
    "ShutdownState",
    "ShutdownPriority",
    "ShutdownHook",
    "ShutdownResult",
    "ShutdownConfig",
    "GracefulShutdown",
    "AgentCoreShutdownManager",
    "get_shutdown_manager",
    "initialize_shutdown",
    "trigger_shutdown",
    "ShutdownGuard",
    # Phase 10: Logging
    "LogLevel",
    "LogCategory",
    "LogContext",
    "StructuredLog",
    "AgentCoreLogger",
    "JsonFormatter",
    "get_logger",
    "log_execution_time",
    "log_tenant_action",
    "PerformanceLogger",
    "redact_value",
    "redact_dict",
    "SENSITIVE_KEYS",
    # Phase 10: API Documentation
    "HTTPStatus",
    "APIResponse",
    "ErrorDetail",
    "PaginationInfo",
    "PaginatedResponse",
    "APIDocHelper",
    "ResponseBuilder",
    "document_endpoint",
    "ExampleGenerator",
    "get_openapi_schema",
    "AGENTCORE_TAGS",
    # Phase 10: Rate Limiting
    "RATE_LIMITING_REGION",
    "RateLimitScope",
    "RateLimitAlgorithm",
    "RateLimitRule",
    "RateLimitResult",
    "TIER_RATE_LIMITS",
    "TokenBucket",
    "SlidingWindowCounter",
    "DistributedRateLimiter",
    "RateLimiterManager",
    "RateLimitError",
    "rate_limit",
    "get_rate_limiter",
    "check_rate_limit",
]
