# ============================================================================
# SUNA DOCKER COMPOSE - DOKPLOY DEPLOYMENT
# ============================================================================
# This Docker Compose file deploys Suna services (Backend, Worker, Frontend, Redis)
# optimized for Dokploy with Traefik reverse proxy.
#
# Services:
#   - Frontend: Next.js application (routed via Traefik)
#   - Backend: Python API (routed via Traefik)
#   - Worker: Background task processor (internal only)
#   - Redis: Caching and message broker (internal only)
#
# Traefik automatically handles routing based on service labels.
# ============================================================================

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
      - ./backend/services/docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: ghcr.io/suna-ai/suna-backend:latest
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/.env:/app/.env:ro
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_SSL=False
    depends_on:
      redis:
        condition: service_healthy
      worker:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`dimatic.com.au`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  worker:
    image: ghcr.io/suna-ai/suna-backend:latest
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run dramatiq --skip-logging --processes 4 --threads 4 run_agent_background
    volumes:
      - ./backend/.env:/app/.env:ro
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_SSL=False
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    init: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`dimatic.com.au`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3015"

volumes:
  redis_data:
